
" Tim Pope's Pathogen plugin for managing vim plugins: https://github.com/tpope/vim-pathogen
filetype off
call pathogen#runtime_append_all_bundles()
filetype plugin indent on
call pathogen#helptags()

set tabstop=4                    " Global tab width
set shiftwidth=4                 " And again, related
set expandtab                    " Use spaces instead of tabs

set ignorecase                    " Case-insensitive searching
set smartcase                     " But case-sensitive if expression contains a capital letter
set incsearch                     " Highlight matches as you type
set hlsearch                      " Highlight matches

set visualbell                    " No beeping

set ruler                         " Show cursor position, ln#, col#
